# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# action 이름
name: deploy

# action 트리거 조건 (release)
# dev 브랜치에 push, pull 할 경우
on: 
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-lastest
    
    steps:
        - name: Checkout source code
          uses: action/checkout@dev

        - name: Cache node modules
          uses: actions/cache@v1
          with:
            path: node_modules
            key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
            restore-key: |
                ${{ runner.OS }}-build-
                ${{ runner.OS }}-
        
        - name: Install Dependencies
          run: npm-install
        
        - name: Build
          run: npm run build

        - name: Deploy
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: |
            aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://mood-classic
